config/routes.rb
SamplesortFoundation::Application.routes.draw do
  resources :samples
  resources :sample_sources
  resources :recordings
  resources :releases
  resources :artists
  resources :searches

  root :to => 'welcome#index'

end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :sample_source
  belongs_to :recording
  attr_accessible :transcript, :sample_source, :recording
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
=begin
# GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @samples }
    end
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    @sample = Sample.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/new
  # GET /samples/new.json
  def new
    @sample = Sample.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.find(params[:id])
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(params[:sample])

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render json: @sample, status: :created, location: @sample }
      else
        format.html { render action: "new" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /samples/1
  # PUT /samples/1.json
  def update
    @sample = Sample.find(params[:id])

    respond_to do |format|
      if @sample.update_attributes(params[:sample])
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to samples_url }
      format.json { head :no_content }
    end
  end
=end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.erb
<%= form_for(@sample) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transcript %><br />
    <%= f.text_field :transcript %>
  </div>
  <div class="field">
    <%= f.label :sample_source %><br />
    <%= f.text_field :sample_source %>
  </div>
  <div class="field">
    <%= f.label :recording %><br />
    <%= f.text_field :recording %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<h1>Samples</h1>

<table>
  <tr>
    <th>Transcript</th>
    <th>Sample source</th>
    <th>Recording</th>
    <th>Artist</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @samples.each do |sample| %>
  <tr>
<!--    <td><%= sample.transcript %></td>-->
    <td><%= link_to sample.transcript, sample_path(sample) %></td>
    <td><%= link_to sample.sample_source.title, sample_source_path(sample.sample_source_id) %></td>
    <td>
    <% if sample.recording -%>
      <%= link_to sample.recording.name, recording_path(sample.recording_id) %>
    <% end -%>
    </td>
    <td>
    <% if (sample.recording and sample.recording.artist) -%>
      <%= link_to sample.recording.artist.name, artist_path(sample.recording.artist_id) %>
    <% end -%>
    </td>

    <td><%= link_to 'Show', sample %></td>
    <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
    <td><%= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sample', new_sample_path %>

app/views/samples/new.html.erb
<h1>New sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Transcript:</b>
  <%= @sample.transcript %>
</p>

<p>
  <b>Sample source:</b>
  <%= @sample.sample_source %>
</p>

<p>
  <b>Recording:</b>
  <%= @sample.recording %>
</p>


<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>