config/routes.rb
SamplesortFoundation::Application.routes.draw do
  resources :samples
  resources :sample_sources
  resources :recordings
  resources :releases
  resources :artists
  resources :searches

  root :to => 'welcome#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name, :display_name
  has_many :recordings
  #has_many :samples, through: :recordings
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.json
  def index
    #@artists = Artist.all
    #@artists = Artist.search(params[:search])
    # Ransack:
    @search = Artist.search(params[:q])
    @artists = @search.result(distinct: true).page(params[:page]).per_page(8)

=begin
    # Pagination with Kaminari:
    #@artists = Artist.page(params[:page]).per(10)
    # will_paginate:
    @artists = Artist.page(params[:page]).per_page(10)
=end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

=begin
  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])

    #@artists = Artist.paginate(:page => params[:page], :per_page => 5)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end
=end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
-->

<div class="row collapse">
  <div class="small-3 columns">
    <%= f.label :name, class: "right inline" %>
  </div>
  <div class="small-9 columns"><%= f.text_field :name %></div>
</div>
<div class="row collapse">
  <div class="small-9 small-offset-3 columns"><%= f.submit %></div>
</div>

<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h3>Artists (and their known samples)</h3>

<div class="artists">
  <%# sort_link @search, :name, "Name" %>
<!--<table>
  <tr>
    <th><%# sort_link @search, :name, "Name" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <%# Kaminari -%>
  <%# paginate(@artists) %>

  <%# will_paginate -%>

  <%# debugger %>
-->

  <%= @artists.length == 0 ? "No results found." : "" %>

  <% @artists.each do |artist| -%>

    <div><span class="radius secondary label"><%= artist.name %></span></div>
    <% if artist.recordings.length == 0 -%>
      <br />
    <% else -%>
      <table>
        <thead>
          <tr>
            <th>Track name</th>
            <th>Sample dialogue</th>
            <th>Sample source</th>
            <th>Album</th>
          </tr>
        </thead>
        <tbody>
        <% artist.recordings.each do |recording| -%>
          <tr>
            <% sample = Sample.find_by_recording_id(recording.id) -%>
            <td><%= recording.name %></td>
            <td><i><%= sample.transcript %></i></td>
            <td><%= sample.sample_source.try(:title) %></td>
            <td><%= recording.release.try(:name) %></td>
          </tr>
        <% end -%>
        </tbody>
      </table>
    <% end -%>
  <% end -%>
</div>

<%# Don't insert pagination HTML if we don't need to -%>
<% if (@artists.total_pages > 1) -%>
  <hr />
  <%# the pagination bar lives in its own foundation row: -%>
  <div class="row">
    <div class="small-12 columns">
<%# debugger %>
      <%= will_paginate(@artists, :class => "digg_pagination") -%>
    </div>
  </div>
<% end -%>

<%#= link_to 'New Artist', new_artist_path, class: "button radius" %>

<hr />
<div class="row">
  <div class="small-6 columns">
  <%= search_form_for @search do |f| -%>
    <div class="field">
      <%= f.label :name_cont, "Search artists by name:" %>
      <%= f.text_field :name_cont %>
    </div>
    <div class="actions"><%= f.submit "Search", class: "small button" %></div>
  <% end -%>
  </div>
</div>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @artist.name %>
</p>
<!-- weird scrolling stuff
<div class="artists">
  <%= render :partial => 'artist', :collection => @artists %>
</div>  
-->


<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>