config/routes.rb
SamplesortFoundation::Application.routes.draw do
  resources :samples
  resources :sample_sources
  resources :recordings
  resources :releases
  resources :artists
  resources :searches

  root :to => 'welcome#index'

end

app/models/recording.rb
class Recording < ActiveRecord::Base
  belongs_to :artist
  belongs_to :release
  attr_accessible :name, :release, :artist
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
=begin
  # GET /recordings
  # GET /recordings.json
  def index
    @recordings = Recording.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recordings }
    end
  end

  # GET /recordings/1
  # GET /recordings/1.json
  def show
    @recording = Recording.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recording }
    end
  end

  # GET /recordings/new
  # GET /recordings/new.json
  def new
    @recording = Recording.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recording }
    end
  end

  # GET /recordings/1/edit
  def edit
    @recording = Recording.find(params[:id])
  end

  # POST /recordings
  # POST /recordings.json
  def create
    @recording = Recording.new(params[:recording])

    respond_to do |format|
      if @recording.save
        format.html { redirect_to @recording, notice: 'Recording was successfully created.' }
        format.json { render json: @recording, status: :created, location: @recording }
      else
        format.html { render action: "new" }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recordings/1
  # PUT /recordings/1.json
  def update
    @recording = Recording.find(params[:id])

    respond_to do |format|
      if @recording.update_attributes(params[:recording])
        format.html { redirect_to @recording, notice: 'Recording was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recordings/1
  # DELETE /recordings/1.json
  def destroy
    @recording = Recording.find(params[:id])
    @recording.destroy

    respond_to do |format|
      format.html { redirect_to recordings_url }
      format.json { head :no_content }
    end
  end
=end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/recordings/_form.html.erb
<%= form_for(@recording) do |f| %>
  <% if @recording.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recording.errors.count, "error") %> prohibited this recording from being saved:</h2>

      <ul>
      <% @recording.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :release %><br />
    <%= f.text_field :release %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recordings/edit.html.erb
<h1>Editing recording</h1>

<%= render 'form' %>

<%= link_to 'Show', @recording %> |
<%= link_to 'Back', recordings_path %>

app/views/recordings/index.html.erb
<!-- <h2>Recordings containing samples</h2> -->
<h1>Recordings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Artist</th>
    <th>Release</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recordings.each do |recording| %>
  <tr>
    <td><%= link_to recording.name, recording_path(recording) %></td>
    <td><%= recording.artist ? (link_to recording.artist.name, artist_path(recording.artist)) : '' %></td>
    <td><%= link_to recording.release.name, release_path(recording.release) %></td>
    <td><%= link_to 'Show', recording %></td>
    <td><%= link_to 'Edit', edit_recording_path(recording) %></td>
    <td><%= link_to 'Destroy', recording, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recording', new_recording_path %>

app/views/recordings/new.html.erb
<h1>New recording</h1>

<%= render 'form' %>

<%= link_to 'Back', recordings_path %>

app/views/recordings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @recording.name %>
</p>

<p>
  <b>Artist:</b>
  <%= @recording.artist.name %>
</p>

<p>
  <b>Release:</b>
  <%= @recording.release.name %>
</p>


<%= link_to 'Edit', edit_recording_path(@recording) %> |
<%= link_to 'Back', recordings_path %>