config/routes.rb
SamplesortFoundation::Application.routes.draw do
  resources :samples
  resources :sample_sources
  resources :recordings
  resources :releases
  resources :artists
  resources :searches

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Samplesort" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44238600-1', 'samplesort.com');
  ga('send', 'pageview');

</script>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "samplesort", "/" %></a></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <!-- empty space in top bar-->
<!--          <li><a href="#" script="onClick:return false;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
          <li class="divider"></li> -->

<!-- I LIKE THIS!!! Go with it once pagination &c are fixed.
          <li class="has-dropdown"><a href="#">Show me all...</a>
            <ul class="dropdown">
              <li class="divider"></li>
              <li><%= link_to "Samples", samples_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sample sources", sample_sources_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Artists", artists_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Recordings", recordings_path %></li>
            </ul>
          </li>
-->


<!--
          <li><%= link_to "Samples", samples_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Sample sources", sample_sources_path %></li>
          <li class="divider"></li>
          <li class="active"><%= link_to "Artists", artists_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Recordings", recordings_path %></li>

          <li class="divider"></li>
-->

<!--
          <li class="has-dropdown"><a href="#">Browse all...</a>
            <ul class="dropdown">
              <li class="divider"></li>
              <li><%= link_to "Samples", samples_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sample sources", sample_sources_path %></li>
              <li class="divider"></li>
              <li class="active"><%= link_to "Artists", artists_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Recordings", recordings_path %></li>
            </ul>
          </li>
-->
        </ul>
      </section>
    </nav>

    <div class="row">
      <div class="small-12 columns"><%= yield %></div>
<%#= yield %>
      <!--
      <div class="small-4 columns">
        <h2 class="subheader">About Us</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
      -->
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <!--<style>#forkongithub a{background:#000;color:#fff;text-decoration:none;font-family:arial, sans-serif;text-align:center;font-weight:bold;padding:5px 40px;font-size:1rem;line-height:2rem;position:relative;transition:0.5s;}#forkongithub a:hover{background:#060;color:#fff;}#forkongithub a::before,#forkongithub a::after{content:"";width:100%;display:block;position:absolute;top:1px;left:0;height:1px;background:#fff;}#forkongithub a::after{bottom:1px;top:auto;}@media screen and (min-width:800px){#forkongithub{position:absolute;display:block;top:0;right:0;width:200px;overflow:hidden;height:200px;}#forkongithub a{width:200px;position:absolute;top:60px;right:-60px;transform:rotate(45deg);-webkit-transform:rotate(45deg);box-shadow:4px 4px 10px rgba(0,0,0,0.8);}}</style><span id="forkongithub"><a href="https://github.com/billagee/samplesort">Fork me on GitHub</a></span> -->
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Samplesort" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44238600-1', 'samplesort.com');
  ga('send', 'pageview');
</script>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "samplesort", "/" %></a></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <!-- empty space in top bar-->
<!--          <li><a href="#" script="onClick:return false;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
          <li class="divider"></li> -->

<!-- I LIKE THIS!!! Go with it once pagination &c are fixed.
          <li class="has-dropdown"><a href="#">Show me all...</a>
            <ul class="dropdown">
              <li class="divider"></li>
              <li><%= link_to "Samples", samples_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sample sources", sample_sources_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Artists", artists_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Recordings", recordings_path %></li>
            </ul>
          </li>
-->


<!--
          <li><%= link_to "Samples", samples_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Sample sources", sample_sources_path %></li>
          <li class="divider"></li>
          <li class="active"><%= link_to "Artists", artists_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Recordings", recordings_path %></li>

          <li class="divider"></li>
-->

<!--
          <li class="divider"></li>
          <li><%= link_to "Browse samples", samples_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Browse sample sources", sample_sources_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Browse artists", artists_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Browse recordings", recordings_path %></li>
-->
        </ul>
      </section>
    </nav>

    <a href="https://github.com/billagee/samplesort"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>

    <div class="row">
      <div class="small-8 columns"><%= yield %></div>
<%#= yield %>

        <div class="small-4 columns"><br />
        <h4 class="subheader">README</h4>
        <div>Samplesort is a resource for music lovers.</div><br />
        <div>Use it to find:</div><br />
        <ul>
          <li>Artists who have used vocal samples</li>
          <li>Songs containing vocal samples</li>
          <li>Movies and other sources whose dialogue has been sampled</li>
        </ul>
        <div><h6 class="subheader">This site is based on Peter Cigéhn's "The Top Sample Lists" (sloth.org/samples). Gone but not forgotten. <%# See the credits page for more. -%></h6></div>
        <div><a href="https://twitter.com/intent/tweet?screen_name=samplesort" class="twitter-mention-button" data-related="wm_agee">Tweet to @samplesort</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></div>
        <div><h4><small>2013 · <a href="http://blog.likewise.org/">Bill Agee</a></small></h4></div>
      </div>

    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>